BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Roles` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
INSERT INTO `Roles` VALUES (1,'Support');
INSERT INTO `Roles` VALUES (2,'Damage');
INSERT INTO `Roles` VALUES (3,'Tank');
CREATE TABLE IF NOT EXISTS `Heros` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`Role`	INTEGER NOT NULL,
	`TotalHealth`	INTEGER NOT NULL,
	`Health`	INTEGER NOT NULL,
	`Armor`	INTEGER,
	`Shield`	INTEGER
);
COMMIT;
